replicaCount: 1

image:
  repository: louislam/uptime-kuma
  tag: 1.23.13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: uptime.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}

